/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SistemaDeReserva.Vistas;

import SistemaDeReserva.Cliente;
import SistemaDeReserva.ClienteData;
import SistemaDeReserva.Conexion;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author arguss
 */
public class ABMClientes extends javax.swing.JInternalFrame {
    private ClienteData clienteData;
    private Conexion conexion;
    

    /**
     * Creates new form ABMClientes
     */
    public ABMClientes() {
        initComponents();
        try {
        conexion = new Conexion("jdbc:mysql://localhost/sistemadereserva", "root", "");
        clienteData = new ClienteData(conexion);
        
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(ABMClientes.class.getName()).log(Level.SEVERE, null, ex);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        btguardarabmcliente = new javax.swing.JButton();
        btborrarabmcliente = new javax.swing.JButton();
        btactualizarabmcliente = new javax.swing.JButton();
        btlimpiarbmcliente = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("ABM CLIENTES");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("ID CLIENTE:");

        jLabel2.setText("PASAPORTE:");

        jLabel3.setText("APELLIDO:");

        jLabel4.setText("NOMBRE:");

        jLabel5.setText("NRO TARJETA:");

        jLabel6.setText("E-MAIL:");

        jTextField1.setToolTipText("");

        btguardarabmcliente.setText("GUARDAR");
        btguardarabmcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btguardarabmclienteActionPerformed(evt);
            }
        });

        btborrarabmcliente.setText("BORRAR");
        btborrarabmcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btborrarabmclienteActionPerformed(evt);
            }
        });

        btactualizarabmcliente.setText("ACTUALIZAR");
        btactualizarabmcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btactualizarabmclienteActionPerformed(evt);
            }
        });

        btlimpiarbmcliente.setText("LIMPIAR");
        btlimpiarbmcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlimpiarbmclienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btguardarabmcliente)
                .addGap(35, 35, 35)
                .addComponent(btborrarabmcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btactualizarabmcliente)
                .addGap(37, 37, 37)
                .addComponent(btlimpiarbmcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4)
                            .addComponent(jTextField5)
                            .addComponent(jTextField6)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1))
                    .addComponent(jLabel3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btguardarabmcliente)
                    .addComponent(btborrarabmcliente)
                    .addComponent(btactualizarabmcliente)
                    .addComponent(btlimpiarbmcliente))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btactualizarabmclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btactualizarabmclienteActionPerformed
        // TODO add your handling code here:
        if (jTextField1.getText()!=null){
            String pasaporte=jTextField2.getText();
            String apellido=jTextField3.getText();
            String nombre=jTextField4.getText();
            String nroTarjeta=jTextField5.getText();
            String email=jTextField6.getText();
            
            Cliente cliente=new Cliente(Integer.parseInt(jTextField1.getText()), pasaporte, apellido, nombre, nroTarjeta, email);
            clienteData.actualizarCliente(cliente);
        }
    }//GEN-LAST:event_btactualizarabmclienteActionPerformed

    private void btguardarabmclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btguardarabmclienteActionPerformed
        // TODO add your handling code here:
        String pasaporte=jTextField2.getText();
        String apellido=jTextField3.getText();
        String nombre=jTextField4.getText();
        String nroTarjeta=jTextField5.getText();
        String email=jTextField6.getText();
        
        Cliente cliente = new Cliente(pasaporte, apellido, nombre, nroTarjeta, email);
        clienteData.guardarCliente(cliente);
        
        jTextField1.setText(cliente.getId_cliente()+"");
    }//GEN-LAST:event_btguardarabmclienteActionPerformed

    private void btborrarabmclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btborrarabmclienteActionPerformed
        // TODO add your handling code here:
        int id=Integer.parseInt(jTextField1.getText());
        clienteData.borrarCliente(id);
    }//GEN-LAST:event_btborrarabmclienteActionPerformed

    private void btlimpiarbmclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlimpiarbmclienteActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
    }//GEN-LAST:event_btlimpiarbmclienteActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btactualizarabmcliente;
    private javax.swing.JButton btborrarabmcliente;
    private javax.swing.JButton btguardarabmcliente;
    private javax.swing.JButton btlimpiarbmcliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
