/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SistemaDeReserva.Vistas;

import SistemaDeReserva.Conexion;
import SistemaDeReserva.Vuelo;
import SistemaDeReserva.VueloData;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author arguss
 */
public class ABMVuelos extends javax.swing.JInternalFrame {
    private VueloData vueloData;
    private Conexion conexion;

    /**
     * Creates new form ABMVuelos
     */
    public ABMVuelos() {
        initComponents();
        try {
        conexion = new Conexion("jdbc:mysql://localhost/backup sistema", "root", "");
        vueloData = new VueloData(conexion);
        
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(ABMVuelos.class.getName()).log(Level.SEVERE, null, ex);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btguardarabmvuelo = new javax.swing.JButton();
        btborrarabmvuelo = new javax.swing.JButton();
        btlimpiarabmvuelo = new javax.swing.JButton();
        btactualizarabmvuelo = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("ABM VUELOS");

        jLabel1.setText("ID VUELO:");

        jLabel2.setText("ID CIUDAD ORIGEN:");

        jLabel3.setText("ID CIUDAD DESTINO:");

        jLabel4.setText("SALIDA:");

        jLabel5.setText("LLEGADA:");

        jLabel6.setText("AEROLINEA:");

        jLabel7.setText("AERONAVE:");

        btguardarabmvuelo.setText("GUARDAR");
        btguardarabmvuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btguardarabmvueloActionPerformed(evt);
            }
        });

        btborrarabmvuelo.setText("BORRAR");
        btborrarabmvuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btborrarabmvueloActionPerformed(evt);
            }
        });

        btlimpiarabmvuelo.setText("LIMPIAR");
        btlimpiarabmvuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlimpiarabmvueloActionPerformed(evt);
            }
        });

        btactualizarabmvuelo.setText("ACTUALIZAR");
        btactualizarabmvuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btactualizarabmvueloActionPerformed(evt);
            }
        });

        jLabel8.setText("ESTADO:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btguardarabmvuelo)
                        .addGap(38, 38, 38)
                        .addComponent(btborrarabmvuelo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(btactualizarabmvuelo)
                        .addGap(38, 38, 38)
                        .addComponent(btlimpiarabmvuelo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField8))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                            .addComponent(jTextField6))))
                                .addGap(87, 87, 87)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btguardarabmvuelo)
                    .addComponent(btborrarabmvuelo)
                    .addComponent(btlimpiarabmvuelo)
                    .addComponent(btactualizarabmvuelo))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btguardarabmvueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btguardarabmvueloActionPerformed
        // TODO add your handling code here:
        int ciudadOrigen=Integer.parseInt(jTextField2.getText());
        int ciudadDestino=Integer.parseInt(jTextField3.getText());
        LocalDate salida=LocalDate.parse(jTextField4.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        LocalDate llegada=LocalDate.parse(jTextField5.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        String aerolinea=jTextField6.getText();
        String aeronave=jTextField7.getText();
        
        Vuelo vuelo = new Vuelo(ciudadOrigen, ciudadDestino, salida, llegada, aerolinea, aeronave);
        vueloData.guardarVuelo(vuelo);
        
        jTextField1.setText(vuelo.getId_vueloNro()+"");
    }//GEN-LAST:event_btguardarabmvueloActionPerformed

    private void btborrarabmvueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btborrarabmvueloActionPerformed
        // TODO add your handling code here:
        int id=Integer.parseInt(jTextField1.getText());
        vueloData.borrarVuelo(id);
    }//GEN-LAST:event_btborrarabmvueloActionPerformed

    private void btactualizarabmvueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btactualizarabmvueloActionPerformed
        // TODO add your handling code here:
         if (jTextField1.getText()!=null){
            int ciudadOrigen=Integer.parseInt(jTextField2.getText());
            int ciudadDestino=Integer.parseInt(jTextField3.getText());
            LocalDate salida=LocalDate.parse(jTextField4.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy"));
            LocalDate llegada=LocalDate.parse(jTextField5.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy"));
            String aerolinea=jTextField6.getText();
            String aeronave=jTextField7.getText();
            String estado=jTextField8.getText();
            
            Vuelo vuelo=new Vuelo(Integer.parseInt(jTextField1.getText()), ciudadOrigen, ciudadDestino, salida, llegada,
                    aerolinea, aeronave, estado);
            vueloData.actualizarVuelo(vuelo);
         }   
    }//GEN-LAST:event_btactualizarabmvueloActionPerformed

    private void btlimpiarabmvueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlimpiarabmvueloActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
    }//GEN-LAST:event_btlimpiarabmvueloActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btactualizarabmvuelo;
    private javax.swing.JButton btborrarabmvuelo;
    private javax.swing.JButton btguardarabmvuelo;
    private javax.swing.JButton btlimpiarabmvuelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
